import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import vectors from '../../public/Vectors-desktop.svg';
import global from './styles/global.module.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const montserrat = localFont({
  src: "./fonts/Montserrat-Medium.woff",
  variable: "--font-montserrat",
  weight: "600",
  style: 'normal',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Waves() {
  return (
    <Image
      priority
      alt="Vectors"
      src={vectors}
      quality={100}
      style={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        zIndex: -1,
        objectFit: 'cover',
        width: '100vw',
        height: 'auto',
      }}
    />
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ fontFamily: montserrat.style.fontFamily }}
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${global['app-container']}`}
      >
        {children}
        <Waves />
      </body>
    </html>
  );
}
